version: "3.9"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-1
      - AWS_DEFAULT_REGION=eu-west-1
      - HOSTNAME_EXTERNAL=localhost
      - USE_SSL=false
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - ./.aws:/docker-entrypoint-initaws.d
  app:
    image: app:latest
    network_mode: bridge
    ports:
      - "5000:5000"

  app-tests:
    image: app-tests:latest
    network_mode: bridge
    depends_on:
      - app
      - localstack
